root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
stop_on_error = true
include_ext = ["go", "yaml", "yml", "toml"]
exclude_dir = ["tmp", "gen"]

[log]
time = true
